language: php

# Added to support travis container infrastructure See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: required

# Added caching support to speed up builds!
cache:
    directories:
    - /usr/local/share/ci-build
    - node_modules

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=1

branches:
 only:
   - master
   - dev
   - develop
   - qa
   - staging
   - ci

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
   # phpunit test cases
   - "phpunit -c tests/phpunit.xml"

   # PHP syntax error checks
   - find ../ \( -name '*.php' \) -exec php -lf {} \;

   # Wordpress Coding Standards
   - $(CODE_SNIFFER_DIR)/scripts/phpcs -p -s -v -n ../ --standard=./tests/codesniffer.ruleset.xml --extensions=php

   # ESLint - Javascript lint tests
   #   Files can be ignored by adding to the .eslintignore file, please see the documentation
   #   provided here: http://eslint.org/docs/user-guide/command-line-interface
   - "$(npm bin)/eslint -f compact ./"

   # CSSLint - CSS line tests
   #   Rules applied come from CI_config, the repo may add files to an exclusion list
   #   by specifying the --exclude-list option like:
   #      csslint --exclude-list=thirdparty.css,tests/
   #   This would ignore the thirdparty.css file and any css files under the tests path
   - "$(npm bin)/csslint --format=compact --quiet ./"

notifications:
  email:
    - kbenedict@postmedia.com