language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=1

branches:
 only:
   - master
   - dev
   - qa
   - staging
   - ci

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
   # phpunit test cases
   - "phpunit -c tests/phpunit.xml"

   # PHP syntax error checks
   - find ../ \( -name '*.php' \) -exec php -lf {} \;

   # Wordpress Coding Standards
   - /tmp/php-codesniffer/scripts/phpcs -p -s -v -n ../ --standard=./tests/codesniffer.ruleset.xml --extensions=php

notifications:
  email:
    - kbenedict@postmedia.com